In [1]:
%matplotlib inline
import random
from time import sleep

import gym
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt


import gym
from gym.wrappers import Monitor
import gym_ple


couldn't import doomish
Couldn't import doom


In [2]:
class Network:
    
    def __init__(self):
        _fc_size = [256, 128, 2]
        self.fully_layers = list()
        n_fc_size = len(_fc_size)
        
        self.imh, self.imw, self.imc = (512, 288, 3)
        self.input_state = tf.placeholder(tf.float32, shape=[None, self.imh, self.imw, self.imc])
        self.gimg = tf.image.rgb_to_grayscale(self.input_state)
        self.rimg = tf.image.resize_images(self.gimg, [80, 80])
        
        self.conv1 = tf.layers.conv2d(self.rimg, 32, 8, activation=tf.nn.relu, strides=(1, 1),)
        self.max1 = tf.layers.max_pooling2d(self.conv1, 2, 2)

        self.conv2 = tf.layers.conv2d(self.max1, 64, 4, activation=tf.nn.relu)
        self.max2 = tf.layers.max_pooling2d(self.conv2, 2, 2)
        
        self.conv3 = tf.layers.conv2d(self.max2, 64, 3, activation=tf.nn.relu)
        self.max3 = tf.layers.max_pooling2d(self.conv3, 2, 2)
#         self.conv3 = tf.layers.conv2d(self.max2, 4, 5, activation=tf.nn.relu)
#         self.max3 = tf.layers.max_pooling2d(self.conv3, 2, 2)

        self.flattern = tf.contrib.layers.flatten(self.max2)
        for i in range(n_fc_size):
            if i == 0:
                self.fully_layers.append( self._create_fc(self.flattern, _fc_size[0]) )
            else:
                self.fully_layers.append( self._create_fc(self.fully_layers[-1], _fc_size[i]) )
        self.pred_Q = self.fully_layers[-1]
        self.select_action = tf.argmax(self.pred_Q, 1)
        self.expect_Q = tf.placeholder(shape=[None, 2], dtype=tf.float32)
        self.loss = tf.losses.mean_squared_error(self.expect_Q, self.pred_Q)
        self.trainer = tf.train.AdamOptimizer(learning_rate=1e-3).minimize(
            loss=self.loss, global_step=tf.train.get_global_step()
        )
    
    def _create_fc(self, input_layer, out_size):
        return tf.contrib.layers.fully_connected(input_layer, out_size, activation_fn=tf.nn.softmax)
    
    def predict(self, sess, state):
        select_action, pred_Q = sess.run([self.select_action, self.pred_Q], \
                                         feed_dict={self.input_state:state})
        return select_action, pred_Q
    
    def update(self, sess, X, Y):
        loss, _ = sess.run([self.loss, self.trainer], feed_dict={self.input_state:X, self.expect_Q:Y})
        return loss
    
class Agent:
    def __init__(self, session, beta=0.9, discount=0.3, batch_iter=10, batch_size=16, max_memory=1000):
        self.sess = session
        self.net = Network()
        self.beta = beta
        self.experience_memory = list()
        self.max_memory = max_memory
        self.batch_size = batch_size
        self.batch_iter = batch_iter
        self.discount = discount
        
    def __enter__(self):
        return self
    
    def __exit__(self, exc_type, exc_value, traceback):
        self.sess.close()
    
    def initvar(self):
        self.sess.run(tf.global_variables_initializer())
        
    def memory(self, pack):
        if len(self.experience_memory) > self.max_memory:
            self.experience_memory.pop(0)
        self.experience_memory.append( pack )
    
    def predict(self, state):
        is_random = False
        select_action, pred_Q = self.net.predict(self.sess, state)
        if np.random.rand(1) < self.beta:
            is_random = True
            select_action = [env.action_space.sample()]
        return select_action, pred_Q, is_random
    
    
    def replay_experience(self):
        losses = list()
        for batchiter in range(self.batch_iter):
            X = list()
            Y = list()
            batch = random.sample(self.experience_memory, \
                min(len(self.experience_memory), self.batch_size))

            for state, action, reward, next_state, done in batch:
                pq = self.predict([state])[1]
                if done:
                    pq[0, action] = reward
                else:
                    pq[0, action] = reward + self.discount * np.max(self.predict([next_state])[1])
                X.append(state)
                Y.append(pq[0])
            loss = self.net.update(sess, np.array(X), np.array(Y))
            losses.append( loss )
        return np.mean(losses)



In [3]:
net = Network()
print(net.max2.shape)
# print(net.gimg.reshape([1, 80, 80, 1]))

(?, 16, 16, 64)


In [ ]:
env = gym.make('FlappyBird-v0')
state = env.reset()
print(state.shape)

(512, 288, 3)


In [ ]:
nepisode = 1000
steps = []
memory = []

with tf.Session() as sess:
    agent = Agent(sess)    
    sess.run(tf.global_variables_initializer())
    
    for episode in range(nepisode+1):
        done = False
        step = 0
        state = env.reset()
        while not done:
            print(np.sum(state), end=' ')
            action, pred_Q, _ = agent.predict([state])
            next_state, reward, done, _ = env.step(action[0])
            
            flat_state = sess.run([agent.net.flattern], feed_dict={agent.net.input_state:[state]})
            print(np.sum(flat_state))
            # Big Penalty to Agent
            if done: 
                reward = -100
            print(pred_Q, reward, end='')
            
            if reward == 0 and np.random.rand(1) < 0.95:
                    pass
            else:
                agent.memory( (state, action, reward, next_state, done) )
                print(' -mem-',end='')
            step += 1
            env.render()
            state = next_state
            print()
        print()
        print()
        steps.append(step)
        agent.beta = agent.beta*0.7    
        if episode%10 == 0 and episode != 0:
            loss = agent.replay_experience()
            print("in Episode {:4d} mean step: {:.2f}, Agent Replay Experience, get loss: {:.2f} "\
                      .format(episode, np.mean(steps[episode-10:episode+1]), loss))

    
    step = 0
    done = False
    state = env.reset()
    while not done:
        action, Q, _ = agent.predict([state])
        state, reward, done, _ = env.step(action[0])
        step += 1
        env.render()
        sleep(0.1)
    print('Bot play game and archive {} step'.format(step))
    env.close()
    

32130 80.8301
[[ 0.50053793  0.49946204]] 0.0
54145472 80610.8
[[ 0.50061107  0.49938893]] 0.0
54145472 80418.1
[[ 0.50061107  0.49938899]] 0.0
54145472 80470.5
[[ 0.50061107  0.49938893]] 0.0
54145472 80668.0
[[ 0.50061113  0.49938896]] 0.0
54145472 80600.9
[[ 0.50061107  0.49938893]] 0.0
54145472 80589.4
[[ 0.50061107  0.49938893]] 0.0
54135392 80297.7
[[ 0.50061113  0.49938896]] 0.0
54105904 80325.4
[[ 0.50061113  0.49938896]] 0.0
54195642 80803.2
[[ 0.50061113  0.49938896]] 0.0
54353796 80768.9
[[ 0.50061107  0.49938893]] 0.0
54580944 80558.6
[[ 0.50061107  0.49938893]] 0.0
54839556 80824.4
[[ 0.50061107  0.49938896]] 0.0
55075824 80741.0
[[ 0.50061107  0.49938893]] 0.0
55265060 80602.0
[[ 0.50061113  0.49938896]] 0.0
55411144 81113.7
[[ 0.50061113  0.49938896]] 0.0
55490558 82164.2
[[ 0.50061113  0.49938896]] 0.0
55513290 83372.1
[[ 0.50061113  0.49938896]] 0.0
55504480 84237.7
[[ 0.50061113  0.49938896]] 0.0
55446196 83768.5
[[ 0.50061113  0.49938896]] 0.0
55439504 85140.8
[[ 0.5

55207332 86459.3
[[ 0.50061113  0.49938896]] 0.0
55211204 86745.7
[[ 0.50061113  0.49938896]] 0.0
55212172 86586.5
[[ 0.50061113  0.49938896]] 0.0
55204480 86668.3
[[ 0.50061113  0.49938896]] 0.0
55204048 86595.4
[[ 0.50061113  0.49938896]] 0.0
55204480 86763.6
[[ 0.50061113  0.49938896]] 0.0
55191184 87259.1
[[ 0.50061113  0.49938896]] 0.0
55170740 86814.7
[[ 0.50061113  0.49938896]] 0.0
55279068 86486.8
[[ 0.50061113  0.49938896]] 0.0
55439392 86275.8
[[ 0.50061113  0.49938896]] 0.0
55658728 85771.5
[[ 0.50061107  0.49938893]] 0.0
55898120 85805.8
[[ 0.50061107  0.49938893]] 0.0
56102632 85530.3
[[ 0.50061107  0.49938893]] 0.0
56249860 85829.3
[[ 0.50061113  0.49938896]] 0.0
56354644 86285.3
[[ 0.50061113  0.49938896]] 0.0
56407024 87233.9
[[ 0.50061113  0.49938896]] 0.0
56416288 87138.0
[[ 0.50061113  0.49938896]] 0.0
56407416 87228.0
[[ 0.50061113  0.49938896]] 0.0
56363300 87258.2
[[ 0.50061113  0.49938896]] 0.0
56361120 87187.0
[[ 0.50061113  0.49938896]] 0.0
56352542 87186.1
[[ 

55208572 87457.7
[[ 0.5006085   0.49939144]] 0.0
55209488 87339.3
[[ 0.50061035  0.49938956]] 0.0
55210404 87712.2
[[ 0.50061101  0.49938908]] 0.0
55212772 87654.4
[[ 0.50061107  0.49938902]] 0.0
55213740 87691.9
[[ 0.50061107  0.49938896]] 0.0
55206532 87790.6
[[ 0.50061107  0.49938893]] 0.0
55206584 87585.2
[[ 0.50061107  0.49938893]] 0.0
55207016 87665.8
[[ 0.50061107  0.49938893]] 0.0
55193720 88229.1
[[ 0.50061107  0.49938893]] 0.0
55144424 88347.1
[[ 0.50061107  0.49938896]] 0.0
55169912 88220.4
[[ 0.50061107  0.49938893]] 0.0
55219280 87955.0
[[ 0.50061107  0.49938893]] 0.0
55322482 87481.2
[[ 0.50061113  0.4993889 ]] 0.0
55467598 87330.5
[[ 0.50061107  0.49938899]] 0.0
55637386 87625.6
[[ 0.50061107  0.49938893]] 0.0
55825330 87620.1
[[ 0.50061101  0.49938899]] 0.0 -mem-
56025778 87816.4
[[ 0.50061107  0.49938896]] 0.0
56194320 88410.8
[[ 0.50061113  0.49938896]] 0.0
56314476 88140.3
[[ 0.50061107  0.49938893]] 0.0
56386478 88082.2
[[ 0.50061107  0.49938893]] 0.0
56366320 88204

55537032 83682.4
[[ 0.50061113  0.49938896]] 0.0
55500616 84635.0
[[ 0.50061113  0.49938896]] 0.0
55433172 84332.1
[[ 0.50061113  0.49938896]] 0.0
55426480 84804.2
[[ 0.50061113  0.49938896]] 0.0
55426160 85552.3
[[ 0.50061113  0.49938896]] 0.0
55422720 86339.9
[[ 0.50061113  0.49938896]] 0.0 -mem-
55411052 87859.7
[[ 0.50061113  0.49938896]] 0.0 -mem-
55410136 88563.8
[[ 0.50061113  0.49938896]] 0.0
55408520 89119.0
[[ 0.50061113  0.49938896]] 0.0
55412168 89426.5
[[ 0.50061113  0.49938896]] 0.0
55409264 89429.0
[[ 0.50061113  0.49938896]] 0.0
55409696 89383.2
[[ 0.50061113  0.49938896]] 0.0
55405964 89385.2
[[ 0.50061113  0.49938896]] 0.0
55399136 89317.1
[[ 0.50061113  0.49938896]] 0.0
55391340 89381.4
[[ 0.50061113  0.49938896]] 0.0
55386016 89772.8
[[ 0.50061113  0.49938896]] 0.0 -mem-
55380260 90326.9
[[ 0.50061113  0.49938896]] 0.0
55380796 91210.7
[[ 0.50061113  0.49938896]] 0.0
55385420 91062.7
[[ 0.50061113  0.49938896]] 0.0
55384832 90986.8
[[ 0.50061113  0.49938896]] 0.0
55

77369138 126512.0
[[ 0.50061113  0.49938896]] 0.0
77366700 126529.0
[[ 0.50061107  0.49938899]] 0.0 -mem-
77365360 125094.0
[[ 0.50061107  0.49938893]] 0.0
77390530 124338.0
[[ 0.50061113  0.49938896]] 0.0
77415516 126683.0
[[ 0.50061113  0.49938896]] -100 -mem-


in Episode   10 mean step: 61.18, Agent Replay Experience, get loss: 1136.25 
77440794 234509.0
[[ 0.49018964  0.50981039]] 0.0
82508884 240239.0
[[ 0.49018964  0.50981039]] 0.0
82508884 240318.0
[[ 0.49018964  0.50981039]] 0.0
82508884 240453.0
[[ 0.49018964  0.50981039]] 0.0
82508884 240578.0
[[ 0.49018964  0.50981039]] 0.0
82508884 240474.0
[[ 0.49018964  0.50981039]] 0.0
82508884 240319.0
[[ 0.49018964  0.50981039]] 0.0
82476628 240224.0
[[ 0.49018964  0.50981039]] 0.0
82137536 240353.0
[[ 0.49018964  0.50981039]] 0.0
81900412 240095.0
[[ 0.49018964  0.50981039]] 0.0
81718868 240461.0
[[ 0.49018964  0.50981039]] 0.0
81603004 240488.0
[[ 0.49018964  0.50981039]] 0.0
81525184 240615.0
[[ 0.49018964  0.50981039]] 0.0
8144695

80972926 240805.0
[[ 0.49018964  0.50981039]] 0.0
80636628 241344.0
[[ 0.49018964  0.50981039]] -100 -mem-


80264176 241085.0
[[ 0.49018964  0.50981039]] 0.0
82527352 239697.0
[[ 0.49018964  0.50981039]] 0.0
82527352 240025.0
[[ 0.49018964  0.50981039]] 0.0
82527352 239963.0
[[ 0.49018964  0.50981039]] 0.0
82527352 239748.0
[[ 0.49018964  0.50981039]] 0.0
82527352 240003.0
[[ 0.49018964  0.50981039]] 0.0
82527352 239995.0
[[ 0.49018964  0.50981039]] 0.0
82495096 239805.0
[[ 0.49018964  0.50981039]] 0.0
82169860 239610.0
[[ 0.49018964  0.50981039]] 0.0
81974532 239639.0
[[ 0.49018964  0.50981039]] 0.0
81835184 239301.0
[[ 0.49018964  0.50981039]] 0.0
81732200 239436.0
[[ 0.49018964  0.50981039]] 0.0
81656592 239644.0
[[ 0.49018964  0.50981039]] 0.0
81599106 239408.0
[[ 0.49018964  0.50981039]] 0.0
81491768 239560.0
[[ 0.49018964  0.50981039]] 0.0
81361158 239719.0
[[ 0.49018964  0.50981039]] 0.0
81221426 240307.0
[[ 0.49018964  0.50981039]] 0.0
80967480 240585.0
[[ 0.49018964  0.509810

54130320 193775.0
[[ 0.484429    0.51557106]] 0.0
54110716 193571.0
[[ 0.484429    0.51557106]] 0.0
54230282 193494.0
[[ 0.484429    0.51557106]] 0.0
54420774 193367.0
[[ 0.484429    0.51557106]] 0.0
54664678 193374.0
[[ 0.484429    0.51557106]] 0.0
54936098 193364.0
[[ 0.484429    0.51557106]] 0.0
55200072 193041.0
[[ 0.484429    0.51557106]] 0.0 -mem-
55390468 193102.0
[[ 0.484429    0.51557106]] 0.0
55529250 194037.0
[[ 0.484429    0.51557106]] 0.0
55611348 194946.0
[[ 0.484429    0.51557106]] 0.0 -mem-
55618252 196176.0
[[ 0.484429    0.51557106]] 0.0
55579366 197534.0
[[ 0.484429    0.51557106]] -100 -mem-


55439188 197838.0
[[ 0.484429    0.51557106]] 0.0
82508884 303714.0
[[ 0.484429    0.51557106]] 0.0
82508884 303817.0
[[ 0.484429    0.51557106]] 0.0
82508884 303792.0
[[ 0.484429    0.51557106]] 0.0
82508884 303792.0
[[ 0.484429    0.51557106]] 0.0
82508884 303910.0
[[ 0.484429    0.51557106]] 0.0
82508884 303737.0
[[ 0.484429    0.51557106]] 0.0
82476628 303680.0
[[ 0.484429

55378292 211486.0
[[ 0.48501566  0.51498431]] 0.0
55387032 212357.0
[[ 0.48501566  0.51498431]] -100 -mem-


55266466 212261.0
[[ 0.48501566  0.51498431]] 0.0
82527352 330811.0
[[ 0.48501566  0.51498431]] 0.0 -mem-
82527352 331061.0
[[ 0.48501566  0.51498431]] 0.0
82527352 330847.0
[[ 0.48501566  0.51498431]] 0.0
82527352 330742.0
[[ 0.48501566  0.51498431]] 0.0
82527352 330954.0
[[ 0.48501566  0.51498431]] 0.0 -mem-
82527352 330763.0
[[ 0.48501566  0.51498431]] 0.0
82495096 330761.0
[[ 0.48501566  0.51498431]] 0.0
82138946 330647.0
[[ 0.48501566  0.51498431]] 0.0
81850362 330465.0
[[ 0.48501566  0.51498431]] 0.0
81581932 330219.0
[[ 0.48501566  0.51498431]] 0.0
81344084 330203.0
[[ 0.48501566  0.51498431]] 0.0
81159588 330257.0
[[ 0.48501566  0.51498431]] 0.0
81063620 330037.0
[[ 0.48501566  0.51498431]] 0.0
80994774 330195.0
[[ 0.48501566  0.51498431]] 0.0
80973040 329991.0
[[ 0.48501566  0.51498431]] 0.0
80968176 330328.0
[[ 0.48501566  0.51498431]] 0.0
80843272 330382.0
[[ 0.485015

82163924 341549.0
[[ 0.49307382  0.50692624]] 0.0 -mem-
81950672 341468.0
[[ 0.49307382  0.50692624]] 0.0 -mem-
81786564 341205.0
[[ 0.49307382  0.50692624]] 0.0
81657688 341223.0
[[ 0.49307382  0.50692624]] 0.0
81561168 341436.0
[[ 0.49307382  0.50692624]] 0.0
81496306 341082.0
[[ 0.49307382  0.50692624]] 0.0 -mem-
81396352 341206.0
[[ 0.49307382  0.50692624]] 0.0
81286662 341352.0
[[ 0.49307382  0.50692624]] 0.0 -mem-
81172826 341727.0
[[ 0.49307382  0.50692624]] 0.0
80943628 342170.0
[[ 0.49307382  0.50692624]] 0.0
80633444 342523.0
[[ 0.49307382  0.50692624]] -100 -mem-


80269650 342268.0
[[ 0.49307382  0.50692624]] 0.0
54127004 217355.0
[[ 0.49307382  0.50692624]] 0.0
54127004 217615.0
[[ 0.49307382  0.50692624]] 0.0
54127004 217671.0
[[ 0.49307382  0.50692624]] 0.0
54127004 217405.0
[[ 0.49307382  0.50692624]] 0.0
54127004 217801.0
[[ 0.49307382  0.50692624]] 0.0
54127004 217418.0
[[ 0.49307382  0.50692624]] 0.0
54116924 217354.0
[[ 0.49307382  0.50692624]] 0.0
54073824 217152.0

in Episode   50 mean step: 19.00, Agent Replay Experience, get loss: 2209.51 
55441578 225029.0
[[ 0.50422007  0.49578002]] 0.0
54127004 220514.0
[[ 0.50422007  0.49578002]] 0.0
54127004 220535.0
[[ 0.50422007  0.49578002]] 0.0
54127004 220356.0
[[ 0.50422007  0.49578002]] 0.0
54127004 220287.0
[[ 0.50422007  0.49578002]] 0.0
54127004 220332.0
[[ 0.50422007  0.49578002]] 0.0
54127004 220332.0
[[ 0.50422007  0.49578002]] 0.0
54116924 220346.0
[[ 0.50422007  0.49578002]] 0.0 -mem-
54080092 220305.0
[[ 0.50422007  0.49578002]] 0.0
54133704 220727.0
[[ 0.50422007  0.49578002]] 0.0
54229332 220829.0
[[ 0.50422007  0.49578002]] 0.0
54379516 220515.0
[[ 0.50422007  0.49578002]] 0.0
54562196 220530.0
[[ 0.50422007  0.49578002]] 0.0
54745408 220648.0
[[ 0.50422007  0.49578002]] 0.0
54908464 219933.0
[[ 0.50422007  0.49578002]] 0.0
55067840 220933.0
[[ 0.50422007  0.49578002]] 0.0
55180864 221604.0
[[ 0.50422007  0.49578002]] 0.0
55247048 222234.0
[[ 0.50422007  0.49578002]] 0.0
55276932 222850.

55207988 231649.0
[[ 0.50422007  0.49578002]] 0.0
55200780 231559.0
[[ 0.50422007  0.49578002]] 0.0
55200832 232002.0
[[ 0.50422007  0.49578002]] 0.0
55201264 232136.0
[[ 0.50422007  0.49578002]] 0.0
55187968 232318.0
[[ 0.50422007  0.49578002]] 0.0
55167126 232016.0
[[ 0.50422007  0.49578002]] 0.0 -mem-
55273214 232123.0
[[ 0.50422007  0.49578002]] 0.0
55431108 232209.0
[[ 0.50422007  0.49578002]] 0.0
55647900 232069.0
[[ 0.50422007  0.49578002]] 0.0
55885218 232183.0
[[ 0.50422007  0.49578002]] 0.0
56087512 232186.0
[[ 0.50422007  0.49578002]] 0.0
56242992 232169.0
[[ 0.50422007  0.49578002]] 0.0
56351314 231917.0
[[ 0.50422007  0.49578002]] 0.0
56406224 232801.0
[[ 0.50422007  0.49578002]] 0.0
56417906 233235.0
[[ 0.50422007  0.49578002]] 0.0
56410820 233767.0
[[ 0.50422007  0.49578002]] 0.0
56367284 234290.0
[[ 0.50422007  0.49578002]] 0.0
56365104 235286.0
[[ 0.50422007  0.49578002]] 0.0
56358502 236167.0
[[ 0.50422007  0.49578002]] 0.0
56355706 237117.0
[[ 0.50422007  0.49578002]

55247836 222210.0
[[ 0.50422007  0.49578002]] 0.0
55277126 222952.0
[[ 0.50422007  0.49578002]] 0.0 -mem-
55236600 222656.0
[[ 0.50422007  0.49578002]] 0.0
55229908 223485.0
[[ 0.50422007  0.49578002]] 0.0
55229588 224461.0
[[ 0.50422007  0.49578002]] 0.0
55226148 225461.0
[[ 0.50422007  0.49578002]] 0.0
55214480 227057.0
[[ 0.50422007  0.49578002]] 0.0
55213564 227966.0
[[ 0.50422007  0.49578002]] 0.0
55211948 229055.0
[[ 0.50422007  0.49578002]] 0.0
55209580 229492.0
[[ 0.50422007  0.49578002]] 0.0
55206676 229207.0
[[ 0.50422007  0.49578002]] 0.0
55207108 229755.0
[[ 0.50422007  0.49578002]] 0.0
55201176 230520.0
[[ 0.50422007  0.49578002]] 0.0
55194348 230683.0
[[ 0.50422007  0.49578002]] 0.0
55188056 230511.0
[[ 0.50422007  0.49578002]] 0.0
55182732 230505.0
[[ 0.50422007  0.49578002]] 0.0
55176976 230985.0
[[ 0.50422007  0.49578002]] 0.0
55177512 231324.0
[[ 0.50422007  0.49578002]] 0.0
55182136 231272.0
[[ 0.50422007  0.49578002]] 0.0
55183052 231247.0
[[ 0.50422007  0.49578002]

77752380 346597.0
[[ 0.50422007  0.49578002]] 0.0
77750724 346709.0
[[ 0.50422007  0.49578002]] 0.0
77755378 344711.0
[[ 0.50422007  0.49578002]] 0.0
77782268 343902.0
[[ 0.50422007  0.49578002]] 0.0
77808400 344242.0
[[ 0.50422007  0.49578002]] -100 -mem-


77833599 344313.0
[[ 0.50422007  0.49578002]] 0.0
82508884 346617.0
[[ 0.50422007  0.49578002]] 0.0
82508884 346548.0
[[ 0.50422007  0.49578002]] 0.0
82508884 346527.0
[[ 0.50422007  0.49578002]] 0.0
82508884 346527.0
[[ 0.50422007  0.49578002]] 0.0
82508884 346418.0
[[ 0.50422007  0.49578002]] 0.0
82508884 346340.0
[[ 0.50422007  0.49578002]] 0.0
82476628 346592.0
[[ 0.50422007  0.49578002]] 0.0
82157790 346661.0
[[ 0.50422007  0.49578002]] 0.0
81963138 346750.0
[[ 0.50422007  0.49578002]] 0.0
81827320 346759.0
[[ 0.50422007  0.49578002]] 0.0
81747606 346849.0
[[ 0.50422007  0.49578002]] 0.0
81685686 346786.0
[[ 0.50422007  0.49578002]] 0.0
81586738 346834.0
[[ 0.50422007  0.49578002]] 0.0 -mem-
81427502 346426.0
[[ 0.50422007  0.

79892332 341357.0
[[ 0.51490241  0.48509753]] 0.0
79891992 341452.0
[[ 0.51490241  0.48509753]] 0.0
79890972 341982.0
[[ 0.51490241  0.48509753]] 0.0
79883600 342185.0
[[ 0.51490241  0.48509753]] 0.0 -mem-
79876488 342287.0
[[ 0.51490241  0.48509753]] 0.0
79868292 342250.0
[[ 0.51490241  0.48509753]] 0.0
79866888 341318.0
[[ 0.51490241  0.48509753]] 0.0
79869012 340968.0
[[ 0.51490241  0.48509753]] 0.0
79832864 341225.0
[[ 0.51490241  0.48509753]] 0.0
79479884 340966.0
[[ 0.51490241  0.48509753]] 0.0
79202072 341045.0
[[ 0.51490241  0.48509753]] 0.0
78943528 342231.0
[[ 0.51490241  0.48509753]] 0.0
78737712 342340.0
[[ 0.51490241  0.48509753]] 0.0
78578400 341844.0
[[ 0.51490241  0.48509753]] 0.0
78452116 341855.0
[[ 0.51490241  0.48509753]] 0.0
78354880 341350.0
[[ 0.51490241  0.48509753]] 0.0
78275680 340742.0
[[ 0.51490241  0.48509753]] 0.0
78162568 341012.0
[[ 0.51490241  0.48509753]] 0.0
77992608 340625.0
[[ 0.51490241  0.48509753]] 0.0
77766680 340354.0
[[ 0.51490241  0.48509753]

54885288 221817.0
[[ 0.51490241  0.48509753]] 0.0
55044276 221237.0
[[ 0.51490241  0.48509753]] 0.0
55178904 222160.0
[[ 0.51490241  0.48509753]] 0.0
55261416 222871.0
[[ 0.51490241  0.48509753]] 0.0
55298476 223524.0
[[ 0.51490241  0.48509753]] 0.0
55308624 224187.0
[[ 0.51490241  0.48509753]] 0.0
55261224 224043.0
[[ 0.51490241  0.48509753]] 0.0 -mem-
55254532 225003.0
[[ 0.51490241  0.48509753]] 0.0
55254212 226141.0
[[ 0.51490241  0.48509753]] 0.0
55250772 227135.0
[[ 0.51490241  0.48509753]] 0.0
55239104 228792.0
[[ 0.51490241  0.48509753]] 0.0
55238188 229530.0
[[ 0.51490241  0.48509753]] 0.0
55236572 230340.0
[[ 0.51490241  0.48509753]] 0.0
55234204 230871.0
[[ 0.51490241  0.48509753]] 0.0 -mem-
55231300 230474.0
[[ 0.51490241  0.48509753]] 0.0
55231732 230964.0
[[ 0.51490241  0.48509753]] 0.0
55228324 232002.0
[[ 0.51490241  0.48509753]] 0.0
55221496 232128.0
[[ 0.51490241  0.48509753]] 0.0
55213700 231765.0
[[ 0.51490241  0.48509753]] 0.0
55208376 231705.0
[[ 0.51490241  0.485

78050726 340471.0
[[ 0.51490241  0.48509753]] 0.0
77768768 340559.0
[[ 0.51490241  0.48509753]] 0.0
77427226 340953.0
[[ 0.51490241  0.48509753]] 0.0
77393430 340941.0
[[ 0.51490241  0.48509753]] 0.0
77370928 339738.0
[[ 0.51490241  0.48509753]] 0.0
77368490 339294.0
[[ 0.51490241  0.48509753]] 0.0
77367150 336360.0
[[ 0.51490241  0.48509753]] 0.0
77392316 334949.0
[[ 0.51490241  0.48509753]] 0.0
77417301 334750.0
[[ 0.51490241  0.48509753]] -100 -mem-


77442593 334523.0
[[ 0.51490241  0.48509753]] 0.0
54145472 221513.0
[[ 0.51490241  0.48509753]] 0.0
54145472 221513.0
[[ 0.51490241  0.48509753]] 0.0
54145472 221410.0
[[ 0.51490241  0.48509753]] 0.0
54145472 221369.0
[[ 0.51490241  0.48509753]] 0.0
54145472 221516.0
[[ 0.51490241  0.48509753]] 0.0
54145472 221606.0
[[ 0.51490241  0.48509753]] 0.0
54135392 221465.0
[[ 0.51490241  0.48509753]] 0.0
54087828 221420.0
[[ 0.51490241  0.48509753]] 0.0
54127596 221751.0
[[ 0.51490241  0.48509753]] 0.0
54216528 221718.0
[[ 0.51490241  0.485097

80056092 347502.0
[[ 0.51490241  0.48509753]] 0.0
80052932 346941.0
[[ 0.51490241  0.48509753]] 0.0
80058620 346607.0
[[ 0.51490241  0.48509753]] 0.0
80068192 346975.0
[[ 0.51490241  0.48509753]] 0.0
80077312 347206.0
[[ 0.51490241  0.48509753]] 0.0
80076972 347351.0
[[ 0.51490241  0.48509753]] 0.0
80075952 347806.0
[[ 0.51490241  0.48509753]] 0.0
80068580 348158.0
[[ 0.51490241  0.48509753]] 0.0
80061468 347929.0
[[ 0.51490241  0.48509753]] 0.0
80053272 347882.0
[[ 0.51490241  0.48509753]] 0.0
80051868 347094.0
[[ 0.51490241  0.48509753]] 0.0
80053992 346615.0
[[ 0.51490241  0.48509753]] 0.0
80017844 347092.0
[[ 0.51490241  0.48509753]] 0.0
79661984 346959.0
[[ 0.51490241  0.48509753]] 0.0
79389336 346962.0
[[ 0.51490241  0.48509753]] 0.0
79149996 348000.0
[[ 0.51490241  0.48509753]] 0.0
78976032 348146.0
[[ 0.51490241  0.48509753]] 0.0
78856372 347650.0
[[ 0.51490241  0.48509753]] 0.0
78770324 347645.0
[[ 0.51490241  0.48509753]] 0.0
78707456 347152.0
[[ 0.51490241  0.48509753]] 0.0


54147836 222192.0
[[ 0.5206393  0.4793607]] 0.0
54258052 222159.0
[[ 0.5206393  0.4793607]] 0.0
54423468 221954.0
[[ 0.5206393  0.4793607]] 0.0
54618532 221988.0
[[ 0.5206393  0.4793607]] 0.0
54806080 222087.0
[[ 0.5206393  0.4793607]] 0.0
54964744 221520.0
[[ 0.5206393  0.4793607]] 0.0 -mem-
55111740 222437.0
[[ 0.5206393  0.4793607]] 0.0
55209516 222989.0
[[ 0.5206393  0.4793607]] 0.0
55261136 223753.0
[[ 0.5206393  0.4793607]] 0.0
55281888 224479.0
[[ 0.5206393  0.4793607]] 0.0
55238016 224208.0
[[ 0.5206393  0.4793607]] 0.0
55231324 225091.0
[[ 0.5206393  0.4793607]] 0.0
55231004 226265.0
[[ 0.5206393  0.4793607]] 0.0
55227564 227165.0
[[ 0.5206393  0.4793607]] 0.0
55215896 228776.0
[[ 0.5206393  0.4793607]] 0.0
55214980 229666.0
[[ 0.5206393  0.4793607]] 0.0
55213364 230573.0
[[ 0.5206393  0.4793607]] 0.0
55210996 231052.0
[[ 0.5206393  0.4793607]] 0.0
55208092 230772.0
[[ 0.5206393  0.4793607]] 0.0
55208524 231287.0
[[ 0.5206393  0.4793607]] 0.0
55202592 232095.0
[[ 0.5206393  0.

77368810 340106.0
[[ 0.5206393  0.4793607]] 0.0
77365778 339576.0
[[ 0.5206393  0.4793607]] 0.0
77364108 337057.0
[[ 0.5206393  0.4793607]] 0.0
77389230 335352.0
[[ 0.5206393  0.4793607]] 0.0 -mem-
77414680 334960.0
[[ 0.5206393  0.4793607]] -100 -mem-


77439932 334637.0
[[ 0.5206393  0.4793607]] 0.0
54140400 222031.0
[[ 0.5206393  0.4793607]] 0.0
54140400 221990.0
[[ 0.5206393  0.4793607]] 0.0
54140400 221905.0
[[ 0.5206393  0.4793607]] 0.0
54140400 221994.0
[[ 0.5206393  0.4793607]] 0.0
54140400 222089.0
[[ 0.5206393  0.4793607]] 0.0
54140400 222044.0
[[ 0.5206393  0.4793607]] 0.0
54130320 221978.0
[[ 0.5206393  0.4793607]] 0.0
54112620 221937.0
[[ 0.5206393  0.4793607]] 0.0
54219296 222210.0
[[ 0.5206393  0.4793607]] 0.0
54387820 222303.0
[[ 0.5206393  0.4793607]] 0.0
54614212 222067.0
[[ 0.5206393  0.4793607]] 0.0
54858908 222098.0
[[ 0.5206393  0.4793607]] 0.0
55062408 222321.0
[[ 0.5206393  0.4793607]] 0.0
55201956 221885.0
[[ 0.5206393  0.4793607]] 0.0
55299488 222744.0
[[ 0.52

80012116 347059.0
[[ 0.5206393  0.4793607]] 0.0
79657172 346794.0
[[ 0.5206393  0.4793607]] 0.0
79385272 346908.0
[[ 0.5206393  0.4793607]] 0.0
79146964 347845.0
[[ 0.5206393  0.4793607]] 0.0
78974080 347996.0
[[ 0.5206393  0.4793607]] 0.0
78855286 347810.0
[[ 0.5206393  0.4793607]] 0.0
78769548 347856.0
[[ 0.5206393  0.4793607]] 0.0
78706370 347308.0
[[ 0.5206393  0.4793607]] 0.0
78649274 346711.0
[[ 0.5206393  0.4793607]] 0.0
78546608 347495.0
[[ 0.5206393  0.4793607]] 0.0
78375428 346903.0
[[ 0.5206393  0.4793607]] 0.0
78139574 346998.0
[[ 0.5206393  0.4793607]] 0.0
77808718 347748.0
[[ 0.5206393  0.4793607]] 0.0
77774922 347963.0
[[ 0.5206393  0.4793607]] 0.0
77752466 347031.0
[[ 0.5206393  0.4793607]] 0.0
77750808 347189.0
[[ 0.5206393  0.4793607]] 0.0 -mem-
77755460 345686.0
[[ 0.5206393  0.4793607]] 0.0
77782344 344271.0
[[ 0.5206393  0.4793607]] 0.0
77808495 344926.0
[[ 0.5206393  0.4793607]] -100 -mem-


77833735 345182.0
[[ 0.5206393  0.4793607]] 0.0
54145472 221956.0
[[ 0.52

55386092 239646.0
[[ 0.5206393  0.4793607]] 0.0
55379264 239970.0
[[ 0.5206393  0.4793607]] 0.0
55372972 239900.0
[[ 0.5206393  0.4793607]] 0.0
55367648 240146.0
[[ 0.5206393  0.4793607]] 0.0
55361892 240585.0
[[ 0.5206393  0.4793607]] 0.0
55362428 240921.0
[[ 0.5206393  0.4793607]] 0.0
55367052 240996.0
[[ 0.5206393  0.4793607]] 0.0
55367968 240864.0
[[ 0.5206393  0.4793607]] 0.0
55368884 240596.0
[[ 0.5206393  0.4793607]] 0.0
55371252 241127.0
[[ 0.5206393  0.4793607]] 0.0
55372972 241054.0
[[ 0.5206393  0.4793607]] 0.0
55365764 240887.0
[[ 0.5206393  0.4793607]] 0.0
55365816 241411.0
[[ 0.5206393  0.4793607]] 0.0
55366248 241498.0
[[ 0.5206393  0.4793607]] 0.0
55352952 241669.0
[[ 0.5206393  0.4793607]] 0.0
55304924 241475.0
[[ 0.5206393  0.4793607]] 0.0
55326364 241572.0
[[ 0.5206393  0.4793607]] 0.0
55382164 241679.0
[[ 0.5206393  0.4793607]] 0.0
55503904 241623.0
[[ 0.5206393  0.4793607]] 0.0
55677888 241676.0
[[ 0.5206393  0.4793607]] 0.0
55884084 241772.0
[[ 0.5206393  0.479360

82495096 349154.0
[[ 0.5234068   0.47659329]] 0.0
82173518 349223.0
[[ 0.5234068   0.47659329]] 0.0
81970624 349265.0
[[ 0.5234068   0.47659329]] 0.0
81823474 349284.0
[[ 0.5234068   0.47659329]] 0.0
81731916 349389.0
[[ 0.5234068   0.47659329]] 0.0
81660316 349447.0
[[ 0.5234068   0.47659329]] 0.0
81557992 349371.0
[[ 0.5234068   0.47659329]] 0.0
81406874 349029.0
[[ 0.5234068   0.47659329]] 0.0
81217378 349557.0
[[ 0.5234068   0.47659329]] 0.0
80972192 349741.0
[[ 0.5234068   0.47659329]] 0.0
80678144 349298.0
[[ 0.5234068   0.47659329]] 0.0
80364112 349292.0
[[ 0.5234068   0.47659329]] 0.0
80007960 348701.0
[[ 0.5234068   0.47659329]] 0.0
79976772 348597.0
[[ 0.5234068   0.47659329]] 0.0
79966632 347981.0
[[ 0.5234068   0.47659329]] 0.0
79952440 347347.0
[[ 0.5234068   0.47659329]] 0.0
79937584 346352.0
[[ 0.5234068   0.47659329]] 0.0
79937200 345086.0
[[ 0.5234068   0.47659329]] 0.0
79936440 344576.0
[[ 0.5234068   0.47659329]] 0.0
79933916 343988.0
[[ 0.5234068   0.47659329]] 0.0


55561830 233844.0
[[ 0.5234068   0.47659329]] 0.0
55775724 233740.0
[[ 0.5234068   0.47659329]] 0.0
55977308 233805.0
[[ 0.5234068   0.47659329]] 0.0
56142492 233858.0
[[ 0.5234068   0.47659329]] 0.0
56272716 233501.0
[[ 0.5234068   0.47659329]] 0.0 -mem-
56356464 234362.0
[[ 0.5234068   0.47659329]] 0.0
56395638 234810.0
[[ 0.5234068   0.47659329]] 0.0
56408628 235277.0
[[ 0.5234068   0.47659329]] 0.0
56370322 235645.0
[[ 0.5234068   0.47659329]] 0.0
56368142 236711.0
[[ 0.5234068   0.47659329]] 0.0
56361540 237582.0
[[ 0.5234068   0.47659329]] 0.0
56358744 238460.0
[[ 0.5234068   0.47659329]] 0.0
56343142 238680.0
[[ 0.5234068   0.47659329]] 0.0
56344248 239428.0
[[ 0.5234068   0.47659329]] 0.0
56341070 240112.0
[[ 0.5234068   0.47659329]] -100 -mem-


56342568 240495.0
[[ 0.5234068   0.47659329]] 0.0
82527352 348991.0
[[ 0.5234068   0.47659329]] 0.0
82527352 348912.0
[[ 0.5234068   0.47659329]] 0.0
82527352 349119.0
[[ 0.5234068   0.47659329]] 0.0
82527352 349188.0
[[ 0.5234068   0.

55414598 236176.0
[[ 0.5234068   0.47659329]] 0.0
55412230 237133.0
[[ 0.5234068   0.47659329]] 0.0
55409326 237359.0
[[ 0.5234068   0.47659329]] 0.0
55409758 238210.0
[[ 0.5234068   0.47659329]] 0.0
55406026 239593.0
[[ 0.5234068   0.47659329]] 0.0 -mem-
55399198 240038.0
[[ 0.5234068   0.47659329]] 0.0
55392906 239808.0
[[ 0.5234068   0.47659329]] 0.0
55387582 239818.0
[[ 0.5234068   0.47659329]] 0.0
55381826 240203.0
[[ 0.5234068   0.47659329]] 0.0
55382362 240494.0
[[ 0.5234068   0.47659329]] 0.0
55386986 240731.0
[[ 0.5234068   0.47659329]] 0.0
55387902 240792.0
[[ 0.5234068   0.47659329]] 0.0
55388818 240592.0
[[ 0.5234068   0.47659329]] 0.0
55391186 240950.0
[[ 0.5234068   0.47659329]] 0.0
55392906 240771.0
[[ 0.5234068   0.47659329]] 0.0
55385698 240643.0
[[ 0.5234068   0.47659329]] 0.0
55385750 241026.0
[[ 0.5234068   0.47659329]] 0.0
55386182 241118.0
[[ 0.5234068   0.47659329]] 0.0
55372886 241507.0
[[ 0.5234068   0.47659329]] 0.0
55320054 241008.0
[[ 0.5234068   0.47659329]

In [ ]:
state = env.reset()

In [ ]:
state